"""Some migration

Revision ID: afb72d6f0e56
Revises: d834de30dea9
Create Date: 2025-08-14 17:32:54.896558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afb72d6f0e56'
down_revision: Union[str, Sequence[str], None] = 'd834de30dea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELED', name='broadcast_status_enum'), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__broadcasts__company_id__companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__broadcasts'))
    )
    op.create_index(op.f('ix__broadcasts_deleted_at'), 'broadcasts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix__broadcasts_id'), 'broadcasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__broadcasts_id'), table_name='broadcasts')
    op.drop_index(op.f('ix__broadcasts_deleted_at'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
