"""Small update

Revision ID: e99438c9164d
Revises: 66f005c88514
Create Date: 2025-06-29 17:05:00.817627

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99438c9164d'
down_revision: Union[str, None] = '66f005c88514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bots',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('bot_type', sa.Enum('CUSTOMER', 'EMPLOYEE', name='bottypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__telegram_bots__company_id__companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__telegram_bots'))
    )
    op.create_index(op.f('ix__telegram_bots_deleted_at'), 'telegram_bots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix__telegram_bots_id'), 'telegram_bots', ['id'], unique=False)
    op.create_index(op.f('ix__telegram_bots_token'), 'telegram_bots', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__telegram_bots_token'), table_name='telegram_bots')
    op.drop_index(op.f('ix__telegram_bots_id'), table_name='telegram_bots')
    op.drop_index(op.f('ix__telegram_bots_deleted_at'), table_name='telegram_bots')
    op.drop_table('telegram_bots')
    # ### end Alembic commands ###
