"""Small fix

Revision ID: 0f726c39d843
Revises: 327f43d29ea9
Create Date: 2025-06-25 14:32:11.725090

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f726c39d843'
down_revision: Union[str, None] = '327f43d29ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__customer_roles__account_id', 'customer_roles', type_='unique')
    op.create_unique_constraint('uq_customer_role_account_company', 'customer_roles', ['account_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_role_account_company', 'customer_roles', type_='unique')
    op.create_unique_constraint('uq__customer_roles__account_id', 'customer_roles', ['account_id'])
    # ### end Alembic commands ###
