"""Fix

Revision ID: 0fd3021a2bbe
Revises:
Create Date: 2025-06-16 23:32:55.687779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fd3021a2bbe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__accounts")),
    )
    op.create_index(
        op.f("ix__accounts_deleted_at"), "accounts", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__accounts_email"), "accounts", ["email"], unique=True)
    op.create_index(op.f("ix__accounts_id"), "accounts", ["id"], unique=False)
    op.create_index(
        op.f("ix__accounts_phone_number"), "accounts", ["phone_number"], unique=True
    )
    op.create_table(
        "tariff_plans",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("internal_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("RUB", "USD", "EUR", name="currency_enum", inherit_schema=True),
            nullable=False,
        ),
        sa.Column(
            "billing_period",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "HALF_YEARLY",
                "ANNUALLY",
                name="tariff_payment_cycle_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("max_outlets", sa.Integer(), nullable=True),
        sa.Column("max_employees", sa.Integer(), nullable=True),
        sa.Column("max_active_promotions", sa.Integer(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                "HIDDEN",
                name="tariff_status_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__tariff_plans")),
        sa.UniqueConstraint(
            "internal_name", name=op.f("uq__tariff_plans__internal_name")
        ),
        sa.UniqueConstraint("name", name=op.f("uq__tariff_plans__name")),
    )
    op.create_index(
        op.f("ix__tariff_plans_deleted_at"),
        "tariff_plans",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix__tariff_plans_id"), "tariff_plans", ["id"], unique=False)
    op.create_index(
        op.f("ix__tariff_plans_status"), "tariff_plans", ["status"], unique=False
    )
    op.create_table(
        "otp_codes",
        sa.Column("hashed_code", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "BACKOFFICE_LOGIN",
                "PHONE_RESET",
                "TRANSACTION_CONFIRM",
                "EMAIL_VERIFICATION",
                name="otp_purpose_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk__otp_codes__account_id__accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__otp_codes")),
    )
    op.create_index(
        op.f("ix__otp_codes_deleted_at"), "otp_codes", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__otp_codes_id"), "otp_codes", ["id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum(
                "FULL_ADMIN",
                "COMPANY_OWNER",
                "COMPANY_MANAGER",
                "SUPPORT_SPECIALIST",
                name="user_access_level_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk__user_roles__account_id__accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_roles")),
        sa.UniqueConstraint("account_id", name=op.f("uq__user_roles__account_id")),
    )
    op.create_index(
        op.f("ix__user_roles_deleted_at"), "user_roles", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user_role_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PENDING_VERIFICATION",
                "SUSPENDED",
                "ARCHIVED",
                name="company_status_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("legal_name", sa.String(length=500), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column(
            "legal_form",
            sa.Enum(
                "OOO",
                "IP",
                "AO",
                "ZAO",
                "SELF_EMPLOYED",
                "OTHER",
                name="legal_form_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("kpp", sa.String(length=9), nullable=True),
        sa.Column("ogrn", sa.String(length=15), nullable=True),
        sa.Column("legal_address", sa.String(length=500), nullable=True),
        sa.Column("representative_full_name", sa.String(length=255), nullable=True),
        sa.Column("bank_name", sa.String(length=255), nullable=True),
        sa.Column("bik", sa.String(length=9), nullable=True),
        sa.Column("correspondent_account", sa.String(length=20), nullable=True),
        sa.Column("payment_account", sa.String(length=20), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_role_id"],
            ["user_roles.id"],
            name=op.f("fk__companies__owner_user_role_id__user_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__companies")),
        sa.UniqueConstraint("ogrn", name=op.f("uq__companies__ogrn")),
    )
    op.create_index(
        op.f("ix__companies_deleted_at"), "companies", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix__companies_inn"), "companies", ["inn"], unique=True)
    op.create_index(op.f("ix__companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix__companies_status"), "companies", ["status"], unique=False)
    op.create_table(
        "cashback",
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "default_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__cashback__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__cashback")),
        sa.UniqueConstraint("company_id", name=op.f("uq__cashback__company_id")),
    )
    op.create_index(
        op.f("ix__cashback_deleted_at"), "cashback", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__cashback_id"), "cashback", ["id"], unique=False)
    op.create_table(
        "customer_roles",
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "cashback_balance",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk__customer_roles__account_id__accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__customer_roles__company_id__companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__customer_roles")),
        sa.UniqueConstraint("account_id", name=op.f("uq__customer_roles__account_id")),
    )
    op.create_index(
        op.f("ix__customer_roles_deleted_at"),
        "customer_roles",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__customer_roles_id"), "customer_roles", ["id"], unique=False
    )
    op.create_table(
        "employee_roles",
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk__employee_roles__account_id__accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__employee_roles__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__employee_roles")),
        sa.UniqueConstraint("account_id", name=op.f("uq__employee_roles__account_id")),
    )
    op.create_index(
        op.f("ix__employee_roles_deleted_at"),
        "employee_roles",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__employee_roles_id"), "employee_roles", ["id"], unique=False
    )
    op.create_table(
        "notification_messages",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("target_segment", sa.String(length=255), nullable=True),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_user_role_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__notification_messages__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_role_id"],
            ["user_roles.id"],
            name=op.f("fk__notification_messages__created_by_user_role_id__user_roles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__notification_messages")),
    )
    op.create_index(
        op.f("ix__notification_messages_deleted_at"),
        "notification_messages",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__notification_messages_id"),
        "notification_messages",
        ["id"],
        unique=False,
    )
    op.create_table(
        "outlets",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "CLOSED_TEMPORARILY",
                "ARCHIVED",
                name="outlet_status_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__outlets__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__outlets")),
    )
    op.create_index(
        op.f("ix__outlets_deleted_at"), "outlets", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__outlets_id"), "outlets", ["id"], unique=False)
    op.create_index(op.f("ix__outlets_status"), "outlets", ["status"], unique=False)
    op.create_table(
        "promotions",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "cashback_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("days_of_week", sa.JSON(), nullable=True),
        sa.Column("start_time", sa.Time(timezone=True), nullable=True),
        sa.Column("end_time", sa.Time(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__promotions__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__promotions")),
    )
    op.create_index(
        op.f("ix__promotions_deleted_at"), "promotions", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix__promotions_id"), "promotions", ["id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_plan_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TRIALING",
                "ACTIVE",
                "PAST_DUE",
                "CANCELED",
                "EXPIRED",
                "INCOMPLETE",
                "INCOMPLETE_EXPIRED",
                "UNPAID",
                name="subscription_status_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("trial_end_date", sa.Date(), nullable=True),
        sa.Column("next_billing_date", sa.Date(), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "current_billing_cycle",
            sa.Enum(
                "MONTHLY",
                "QUARTERLY",
                "HALF_YEARLY",
                "ANNUALLY",
                name="subscription_payment_cycle_enum",
                inherit_schema=True,
            ),
            nullable=True,
        ),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__subscriptions__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tariff_plan_id"],
            ["tariff_plans.id"],
            name=op.f("fk__subscriptions__tariff_plan_id__tariff_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__subscriptions")),
    )
    op.create_index(
        op.f("ix__subscriptions_company_id"),
        "subscriptions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__subscriptions_deleted_at"),
        "subscriptions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix__subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix__subscriptions_next_billing_date"),
        "subscriptions",
        ["next_billing_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix__subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix__subscriptions_tariff_plan_id"),
        "subscriptions",
        ["tariff_plan_id"],
        unique=False,
    )
    op.create_table(
        "employee_role_outlet_association",
        sa.Column("employee_role_id", sa.BigInteger(), nullable=False),
        sa.Column("outlet_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_role_id"],
            ["employee_roles.id"],
            name=op.f(
                "fk__employee_role_outlet_association__employee_role_id__employee_roles"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["outlet_id"],
            ["outlets.id"],
            name=op.f("fk__employee_role_outlet_association__outlet_id__outlets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "employee_role_id",
            "outlet_id",
            name=op.f("pk__employee_role_outlet_association"),
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("purchase_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "cashback_accrued", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("cashback_spent", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "transaction_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("performed_by_employee_id", sa.BigInteger(), nullable=True),
        sa.Column("customer_role_id", sa.BigInteger(), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("outlet_id", sa.BigInteger(), nullable=True),
        sa.Column("applied_promotion_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["applied_promotion_id"],
            ["promotions.id"],
            name=op.f("fk__transactions__applied_promotion_id__promotions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk__transactions__company_id__companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_role_id"],
            ["customer_roles.id"],
            name=op.f("fk__transactions__customer_role_id__customer_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["outlet_id"],
            ["outlets.id"],
            name=op.f("fk__transactions__outlet_id__outlets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_employee_id"],
            ["employee_roles.id"],
            name=op.f("fk__transactions__performed_by_employee_id__employee_roles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__transactions")),
    )
    op.create_index(
        op.f("ix__transactions_deleted_at"),
        "transactions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix__transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix__transactions_performed_by_employee_id"),
        "transactions",
        ["performed_by_employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__transactions_performed_by_employee_id"), table_name="transactions"
    )
    op.drop_index(op.f("ix__transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix__transactions_deleted_at"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("employee_role_outlet_association")
    op.drop_index(op.f("ix__subscriptions_tariff_plan_id"), table_name="subscriptions")
    op.drop_index(op.f("ix__subscriptions_status"), table_name="subscriptions")
    op.drop_index(
        op.f("ix__subscriptions_next_billing_date"), table_name="subscriptions"
    )
    op.drop_index(op.f("ix__subscriptions_id"), table_name="subscriptions")
    op.drop_index(op.f("ix__subscriptions_deleted_at"), table_name="subscriptions")
    op.drop_index(op.f("ix__subscriptions_company_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix__promotions_id"), table_name="promotions")
    op.drop_index(op.f("ix__promotions_deleted_at"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index(op.f("ix__outlets_status"), table_name="outlets")
    op.drop_index(op.f("ix__outlets_id"), table_name="outlets")
    op.drop_index(op.f("ix__outlets_deleted_at"), table_name="outlets")
    op.drop_table("outlets")
    op.drop_index(
        op.f("ix__notification_messages_id"), table_name="notification_messages"
    )
    op.drop_index(
        op.f("ix__notification_messages_deleted_at"), table_name="notification_messages"
    )
    op.drop_table("notification_messages")
    op.drop_index(op.f("ix__employee_roles_id"), table_name="employee_roles")
    op.drop_index(op.f("ix__employee_roles_deleted_at"), table_name="employee_roles")
    op.drop_table("employee_roles")
    op.drop_index(op.f("ix__customer_roles_id"), table_name="customer_roles")
    op.drop_index(op.f("ix__customer_roles_deleted_at"), table_name="customer_roles")
    op.drop_table("customer_roles")
    op.drop_index(op.f("ix__cashback_id"), table_name="cashback")
    op.drop_index(op.f("ix__cashback_deleted_at"), table_name="cashback")
    op.drop_table("cashback")
    op.drop_index(op.f("ix__companies_status"), table_name="companies")
    op.drop_index(op.f("ix__companies_name"), table_name="companies")
    op.drop_index(op.f("ix__companies_inn"), table_name="companies")
    op.drop_index(op.f("ix__companies_id"), table_name="companies")
    op.drop_index(op.f("ix__companies_deleted_at"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix__user_roles_id"), table_name="user_roles")
    op.drop_index(op.f("ix__user_roles_deleted_at"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix__otp_codes_id"), table_name="otp_codes")
    op.drop_index(op.f("ix__otp_codes_deleted_at"), table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_index(op.f("ix__tariff_plans_status"), table_name="tariff_plans")
    op.drop_index(op.f("ix__tariff_plans_id"), table_name="tariff_plans")
    op.drop_index(op.f("ix__tariff_plans_deleted_at"), table_name="tariff_plans")
    op.drop_table("tariff_plans")
    op.drop_index(op.f("ix__accounts_phone_number"), table_name="accounts")
    op.drop_index(op.f("ix__accounts_id"), table_name="accounts")
    op.drop_index(op.f("ix__accounts_email"), table_name="accounts")
    op.drop_index(op.f("ix__accounts_deleted_at"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
