"""All models have been implemented

Revision ID: 2a3abea33c30
Revises: 0912290d8d5f
Create Date: 2025-05-19 23:11:15.944390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3abea33c30'
down_revision: Union[str, None] = '0912290d8d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('requisites', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk__companies__owner_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__companies')),
    sa.UniqueConstraint('ogrn', name=op.f('uq__companies__ogrn'))
    )
    op.create_index(op.f('ix__companies_inn'), 'companies', ['inn'], unique=True)
    op.create_index(op.f('ix__companies_name'), 'companies', ['name'], unique=False)
    op.create_table('cashback_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('default_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__cashback_configs__company_id__companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cashback_configs')),
    sa.UniqueConstraint('company_id', name=op.f('uq__cashback_configs__company_id'))
    )
    op.create_table('customers',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('device_token', sa.Text(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__customers__company_id__companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__customers'))
    )
    op.create_index(op.f('ix__customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_table('employees',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__employees__company_id__companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__employees'))
    )
    op.create_index(op.f('ix__employees_phone_number'), 'employees', ['phone_number'], unique=True)
    op.create_table('notification_messages',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_segment', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__notification_messages__company_id__companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk__notification_messages__created_by_user_id__users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__notification_messages'))
    )
    op.create_table('outlets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__outlets__company_id__companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__outlets'))
    )
    op.create_table('promotions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cashback_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Time(timezone=True), nullable=True),
    sa.Column('end_time', sa.Time(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__promotions__company_id__companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__promotions'))
    )
    op.create_table('employee_outlet_association',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk__employee_outlet_association__employee_id__employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk__employee_outlet_association__outlet_id__outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'outlet_id', name=op.f('pk__employee_outlet_association'))
    )
    op.create_table('transactions',
    sa.Column('purchase_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashback_accrued', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashback_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('outlet_id', sa.BigInteger(), nullable=True),
    sa.Column('applied_promotion_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_promotion_id'], ['promotions.id'], name=op.f('fk__transactions__applied_promotion_id__promotions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__transactions__company_id__companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk__transactions__customer_id__customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk__transactions__outlet_id__outlets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__transactions'))
    )
    op.drop_table('business_partner_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_partner_profiles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk__business_partner_profiles__user_id__users'),
    sa.PrimaryKeyConstraint('id', name='pk__business_partner_profiles'),
    sa.UniqueConstraint('user_id', name='uq__business_partner_profiles__user_id')
    )
    op.drop_table('transactions')
    op.drop_table('employee_outlet_association')
    op.drop_table('promotions')
    op.drop_table('outlets')
    op.drop_table('notification_messages')
    op.drop_index(op.f('ix__employees_phone_number'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix__customers_phone_number'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('cashback_configs')
    op.drop_index(op.f('ix__companies_name'), table_name='companies')
    op.drop_index(op.f('ix__companies_inn'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
