"""Refactoring

Revision ID: 327f43d29ea9
Revises: 6119842373e9
Create Date: 2025-06-24 10:58:29.338115

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '327f43d29ea9'
down_revision: Union[str, None] = '6119842373e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('telegram_user_id', sa.BigInteger(), nullable=True))
    op.add_column('accounts', sa.Column('telegram_username', sa.String(), nullable=True))
    op.create_index(op.f('ix__accounts_telegram_user_id'), 'accounts', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix__accounts_telegram_username'), 'accounts', ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__accounts_telegram_username'), table_name='accounts')
    op.drop_index(op.f('ix__accounts_telegram_user_id'), table_name='accounts')
    op.drop_column('accounts', 'telegram_username')
    op.drop_column('accounts', 'telegram_user_id')
    # ### end Alembic commands ###
