"""Small fix

Revision ID: 66f005c88514
Revises: f0c668acb16a
Create Date: 2025-06-28 21:32:35.997367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66f005c88514'
down_revision: Union[str, None] = 'f0c668acb16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_roles', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('otp_codes', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'meta')
    op.alter_column('customer_roles', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
