"""Remaster model

Revision ID: 697dc88d188f
Revises: 0fd3021a2bbe
Create Date: 2025-06-18 18:43:01.092466

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "697dc88d188f"
down_revision: Union[str, None] = "0fd3021a2bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_roles",
        sa.Column("work_phone_number", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "employee_roles",
        sa.Column("work_full_name", sa.String(length=555), nullable=True),
    )
    op.add_column(
        "employee_roles", sa.Column("work_email", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix__employee_roles_work_email"),
        "employee_roles",
        ["work_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix__employee_roles_work_phone_number"),
        "employee_roles",
        ["work_phone_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__employee_roles_work_phone_number"), table_name="employee_roles"
    )
    op.drop_index(op.f("ix__employee_roles_work_email"), table_name="employee_roles")
    op.drop_column("employee_roles", "work_email")
    op.drop_column("employee_roles", "work_full_name")
    op.drop_column("employee_roles", "work_phone_number")
    # ### end Alembic commands ###
