"""Some models updated

Revision ID: 8dcbd52fef49
Revises: af4ab3ae4cbd
Create Date: 2025-05-25 23:06:59.985597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcbd52fef49'
down_revision: Union[str, None] = 'af4ab3ae4cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('hashed_code', sa.String(length=255), nullable=False))
    op.drop_column('otp_codes', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('otp_codes', 'hashed_code')
    # ### end Alembic commands ###
