"""Some models fixed

Revision ID: a3a64569eace
Revises: d645fdda9b76
Create Date: 2025-05-26 15:48:11.249032

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3a64569eace"
down_revision: Union[str, None] = "d645fdda9b76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_codes",
        sa.Column(
            "purpose",
            sa.Enum(
                "BACKOFFICE_LOGIN",
                "PHONE_RESET",
                "TRANSACTION_CONFIRM",
                "EMAIL_VERIFICATION",
                name="otp_purpose_enum",
                inherit_schema=True,
                create_constraint=True,
            ),
            nullable=False,
        ),
    )
    op.drop_column("otp_codes", "otp_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_codes",
        sa.Column(
            "otp_type",
            postgresql.ENUM(
                "LOGIN",
                "PASSWORD_RESET",
                "TRANSACTION_CONFIRM",
                "EMAIL_VERIFICATION",
                name="otp_type_enum",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("otp_codes", "purpose")
    # ### end Alembic commands ###
