"""Small fix

Revision ID: f0c668acb16a
Revises: ee23259a034f
Create Date: 2025-06-27 23:18:05.448480

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0c668acb16a"
down_revision: Union[str, None] = "ee23259a034f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE otp_purpose_enum ADD VALUE 'TRANSACTION_CONFIRMATION'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
